FROM python:3.9
WORKDIR /src

# Install Python requirements
RUN pip install --upgrade pip
# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY pyproject.toml poetry.lock* /src/

RUN poetry install --no-root

COPY . .

ENTRYPOINT tests/_wait_for_it.sh -q db:5432 -- pytest tests/test_plpy_func.py -vv
